### ISSUE TITLE
Chain is not correct computed

### ISSUE THREAD

**Issue by Mastaleru** [webcardinal/webcardinal-core#10]
The html structure is

```
<... data-for="@pagination.items">
<webc-template data-view-model="@kitsDispensed">
<webc-container data-view-model="@"></webcontainer>
</webc-template>
<../>
```

The chain should be pagination.items.[0...n].kitsDispensed and it is pagination.items.kitsDispensed

![pagination-chain](https://user-images.githubusercontent.com/1469129/139291349-4de5f469-19bf-4c96-bb2e-730bfd5378b9.png)

**Comment by denypatrascu** [comment]
Since the latest modifications made for psk-bindable-model, this issue was fixed.

Commit no: 0bc63f72c8db6065aa714ea44af90672ebfda0ed

Check the following test: https://webcardinal.github.io/webcardinal-app-tester/tests/manual/webc-container/test-2
